/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.DaoQuartos;
import enums.Status;
import enums.TipoQuarto;
import java.math.BigDecimal;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Quartos;

/**
 *
 * @author Administrador
 */
public class DialogQuartos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogQuartos.class.getName());
    
    //Carregar os Dados da Table
    private DaoQuartos dao = new DaoQuartos();
    
    //Carregar os dados da table
    private void loadTable(){
        Table.setModel(new MyTableModel(Quartos.class, dao.read(), Table));
    }
    
    //Carregar table com o filtro do Numero do Quarto
    private void loadTable(String filtro){
        Table.setModel(new MyTableModel(Quartos.class, dao.readByNumeroQuartos(filtro), Table));
    }
    
    //Zerar Componentes
    private void limparComponentes(){
        TCodigo.setText("");
        TNumeroQuarto.setText("");
        CTipoQuarto.setSelectedIndex(0);
        FTValorDiaria.setValue(0.0);
        CStatus.setSelectedIndex(0);
        TFiltro.setText("");
        TNumeroQuarto.requestFocus();
    }
    
    // Montar Objeto
    private Quartos createObject(){
        Quartos q = new Quartos();
        
        if(TCodigo.getText().isEmpty()){
            q.setId(0);
        } else {
            q.setId(Integer.parseInt(TCodigo.getText()));
        }
        
        q.setNumero_quarto(TNumeroQuarto.getText());
        q.setTipo_quarto((TipoQuarto) CTipoQuarto.getSelectedItem());
        q.setStatus((Status) CStatus.getSelectedItem());
        Object valor = FTValorDiaria.getValue();
        BigDecimal preco;
        if (valor == null) {
            preco = BigDecimal.ZERO; 
        } else {
            try {
                preco = BigDecimal.valueOf(((Number) valor).doubleValue());
            } catch (Exception e) {
                preco = BigDecimal.ZERO;
            }
        }
        q.setPreco_diaria(preco);
        return q;
    }
    
    //Popular Componentes
    private void loadComponents(Quartos q){
        TCodigo.setText(q.getId()+"");
        TNumeroQuarto.setText(q.getNumero_quarto());
        CTipoQuarto.setSelectedItem(q.getTipo_quarto());
        CStatus.setSelectedItem(q.getStatus());
        FTValorDiaria.setValue(q.getPreco_diaria());
    }
    
    //Carregar Enums
    private void loadTipoQuarto(){
        DefaultComboBoxModel cbm = new DefaultComboBoxModel(TipoQuarto.values());
        CTipoQuarto.setModel(cbm);
    }
    private void loadStatus(){
        DefaultComboBoxModel cbm = new DefaultComboBoxModel(Status.values());
        CStatus.setModel(cbm);
        
    }

    /**
     * Creates new form DialogQuartos
     */
    public DialogQuartos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TNumeroQuarto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CTipoQuarto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        FTValorDiaria = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        CStatus = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        BtnSalvar = new javax.swing.JButton();
        BtnNovo = new javax.swing.JButton();
        BtnRemover = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TFiltro = new javax.swing.JTextField();
        BtnFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Codigo");

        TCodigo.setEditable(false);

        jLabel2.setText("Numero do Quarto");

        jLabel3.setText("Tipo do Quarto");

        CTipoQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Valor da Diaria");

        FTValorDiaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
            new javax.swing.text.NumberFormatter(
                new java.text.DecimalFormat("#,##0.00")
            )
        )
    );
    FTValorDiaria.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            FTValorDiariaActionPerformed(evt);
        }
    });

    jLabel5.setText("Status do Quarto");

    CStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel4)
                .addComponent(CTipoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                    .addComponent(FTValorDiaria, javax.swing.GroupLayout.Alignment.LEADING))
                .addComponent(TNumeroQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1)
                .addComponent(TCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(192, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(TCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(TNumeroQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(CTipoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(FTValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(CStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(25, Short.MAX_VALUE))
    );

    BtnSalvar.setText("Salvar");
    BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnSalvarActionPerformed(evt);
        }
    });

    BtnNovo.setText("Novo");
    BtnNovo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnNovoActionPerformed(evt);
        }
    });

    BtnRemover.setText("Remover");
    BtnRemover.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnRemoverActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(69, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(BtnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(BtnSalvar)
            .addGap(18, 18, 18)
            .addComponent(BtnNovo)
            .addGap(18, 18, 18)
            .addComponent(BtnRemover)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel6.setText("Filtro");

    BtnFiltrar.setText("Filtrar");
    BtnFiltrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnFiltrarActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(TFiltro)
            .addGap(18, 18, 18)
            .addComponent(BtnFiltrar)
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap(21, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(TFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(BtnFiltrar))
            .addGap(13, 13, 13))
    );

    Table.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    Table.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            TableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(Table);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FTValorDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTValorDiariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTValorDiariaActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        Quartos q = this.createObject();
        String numero = TNumeroQuarto.getText().trim();
        if (numero.length() > 4) {
            JOptionPane.showMessageDialog(this,
                    "O número do quarto deve ter no máximo 4 caracteres (ex: AB24).",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            TNumeroQuarto.requestFocus();
            return;
        }
        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "O número do quarto não pode estar vazio.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            TNumeroQuarto.requestFocus();
            return;
        }
        
        
        try{
            if(TCodigo.getText().isEmpty()){
                dao.create(q);
                JOptionPane.showMessageDialog(null, "Registro Criado com Sucesso");
            }else{
                dao.update(q);
                JOptionPane.showMessageDialog(null, "Registro Atualizado com Sucesso");
            }
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Erro ao Gravar" + ex.getMessage());
        }
        this.limparComponentes();
        this.loadTable();
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        this.limparComponentes();
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoverActionPerformed
        if(TCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Selecione Um dos Registros");
            return;
        }
        if(JOptionPane.showConfirmDialog(null,"Deseja Remover") != 0){
            return;
        }
        try{
            int codigo = Integer.parseInt(TCodigo.getText());
            Quartos q = dao.read(Quartos.class, codigo);
            dao.delete(q);
            JOptionPane.showMessageDialog(null, "Registro Removido com Sucesso");
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null,"Erro" + ex.getMessage());
        }
        this.limparComponentes();
        this.loadTable();
    }//GEN-LAST:event_BtnRemoverActionPerformed

    private void BtnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFiltrarActionPerformed
        this.loadTable(TFiltro.getText());
    }//GEN-LAST:event_BtnFiltrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.loadTable();
        this.loadTipoQuarto();
        this.loadStatus();
    }//GEN-LAST:event_formWindowOpened

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        if(evt.getClickCount() == 2){
            int selecionado = (Integer)Table.getValueAt(Table.getSelectedRow(), 0);
            Quartos q = dao.read(Quartos.class, selecionado);
            this.loadComponents(q);
        }
    }//GEN-LAST:event_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogQuartos dialog = new DialogQuartos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFiltrar;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnRemover;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JComboBox<String> CStatus;
    private javax.swing.JComboBox<String> CTipoQuarto;
    private javax.swing.JFormattedTextField FTValorDiaria;
    private javax.swing.JTextField TCodigo;
    private javax.swing.JTextField TFiltro;
    private javax.swing.JTextField TNumeroQuarto;
    private javax.swing.JTable Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
