/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author Administrador
 */
public class FrameMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameMenu.class.getName());

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        IHospedes = new javax.swing.JMenuItem();
        IQuartos = new javax.swing.JMenuItem();
        IReserva = new javax.swing.JMenuItem();
        IPagamentos = new javax.swing.JMenuItem();
        IAvaliacaoQuartos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Hotel");

        IHospedes.setText("Hospedes");
        IHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IHospedesActionPerformed(evt);
            }
        });
        jMenu1.add(IHospedes);

        IQuartos.setText("Quartos");
        IQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IQuartosActionPerformed(evt);
            }
        });
        jMenu1.add(IQuartos);

        IReserva.setText("Reservas");
        IReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IReservaActionPerformed(evt);
            }
        });
        jMenu1.add(IReserva);

        IPagamentos.setText("Pagamentos");
        IPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPagamentosActionPerformed(evt);
            }
        });
        jMenu1.add(IPagamentos);

        IAvaliacaoQuartos.setText("Avaliação Quarto");
        IAvaliacaoQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IAvaliacaoQuartosActionPerformed(evt);
            }
        });
        jMenu1.add(IAvaliacaoQuartos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IHospedesActionPerformed
        new DialogHospedes(this, true).setVisible(true);
    }//GEN-LAST:event_IHospedesActionPerformed

    private void IQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IQuartosActionPerformed
        new DialogQuartos(this, true).setVisible(true);
    }//GEN-LAST:event_IQuartosActionPerformed

    private void IReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IReservaActionPerformed
        new DialogReservas(this, true).setVisible(true);
    }//GEN-LAST:event_IReservaActionPerformed

    private void IPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPagamentosActionPerformed
        new DialogPagamento(this, true).setVisible(true);
    }//GEN-LAST:event_IPagamentosActionPerformed

    private void IAvaliacaoQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IAvaliacaoQuartosActionPerformed
        new DialogAvaliacaoQuarto(this, true).setVisible(true);
    }//GEN-LAST:event_IAvaliacaoQuartosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem IAvaliacaoQuartos;
    private javax.swing.JMenuItem IHospedes;
    private javax.swing.JMenuItem IPagamentos;
    private javax.swing.JMenuItem IQuartos;
    private javax.swing.JMenuItem IReserva;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
